export interface DeliveryAreaSEO {
  slug: string;
  name: string;
  shortName: string;
  city: 'Islamabad' | 'Rawalpindi';
  deliveryType: 'Free Doorstep Delivery' | 'Dedicated Rider Express Delivery';
  deliveryFee: string;
  deliveryTimeMorning: string;
  deliveryTimeEvening: string;
  description: string;
  landmarks: string[];
  postalCode?: string;
  popularProducts: string[];
}

export const DELIVERY_AREAS: DeliveryAreaSEO[] = [
  {
    slug: 'shahzad-town',
    name: 'Shahzad Town & Chak Shahzad',
    shortName: 'Shahzad Town',
    city: 'Islamabad',
    deliveryType: 'Free Doorstep Delivery',
    deliveryFee: '100% FREE Delivery',
    deliveryTimeMorning: '6:00 AM – 8:30 AM',
    deliveryTimeEvening: '4:30 PM – 7:00 PM',
    description: 'Direct farm doorstep delivery in Shahzad Town and Chak Shahzad. Chilled fresh cow milk delivered within minutes of milking at our Park Road farm hub.',
    landmarks: ['Park Road', 'Chak Shahzad Farm Houses', 'NARC', 'COMSATS Road'],
    postalCode: '44000',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'Fresh Desi Makhan', 'Bilona Desi Ghee', 'Probiotic Dahi'],
  },
  {
    slug: 'sector-i-8',
    name: 'Sector I-8 (I-8/1, I-8/2, I-8/3, I-8/4)',
    shortName: 'Sector I-8',
    city: 'Islamabad',
    deliveryType: 'Free Doorstep Delivery',
    deliveryFee: '100% FREE Delivery',
    deliveryTimeMorning: '6:30 AM – 8:45 AM',
    deliveryTimeEvening: '5:00 PM – 7:30 PM',
    description: '100% Free daily fresh cow milk delivery across all sub-sectors of I-8 (I-8/1, I-8/2, I-8/3, I-8/4) and I-8 Markaz. Zero delivery charges.',
    landmarks: ['I-8 Markaz', 'Kachnar Park', 'Habib Bank Road', 'I-8/3 Park'],
    postalCode: '44080',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'Organic Dahi', 'Pure Desi Ghee', 'Fresh Paneer'],
  },
  {
    slug: 'sector-i-9',
    name: 'Sector I-9 (I-9/1, I-9/2, I-9/3, I-9/4)',
    shortName: 'Sector I-9',
    city: 'Islamabad',
    deliveryType: 'Free Doorstep Delivery',
    deliveryFee: '100% FREE Delivery',
    deliveryTimeMorning: '6:30 AM – 8:45 AM',
    deliveryTimeEvening: '5:00 PM – 7:30 PM',
    description: '100% Free doorstep delivery of pure pasture cow milk in Sector I-9 residential and commercial areas. Lab certified chemical-free.',
    landmarks: ['I-9 Markaz', 'I-9/4 Residential', 'Potohar Road', 'Industrial Area'],
    postalCode: '44090',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'Bilona Cow Ghee', 'Fresh Dahi', 'Pure Makhan'],
  },
  {
    slug: 'bahria-town-islamabad',
    name: 'Bahria Town (Phases 1 to 8 & Safari Villas)',
    shortName: 'Bahria Town',
    city: 'Islamabad',
    deliveryType: 'Dedicated Rider Express Delivery',
    deliveryFee: 'Standard Rider Delivery',
    deliveryTimeMorning: '6:00 AM – 8:30 AM',
    deliveryTimeEvening: '5:00 PM – 7:30 PM',
    description: 'Chilled, temperature-controlled morning cow milk delivery to all phases of Bahria Town Islamabad & Rawalpindi (Phases 1-8, Safari Valley, Executive Lodges).',
    landmarks: ['Civic Center', 'Phase 4 River View', 'Phase 7 Commercial', 'Phase 8 Hub', 'Safari Villas'],
    postalCode: '46220',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'Bilona Desi Ghee', 'Fresh Country Butter', 'Natural Dahi'],
  },
  {
    slug: 'dha-islamabad',
    name: 'DHA Islamabad (Phases 1, 2, 3, 5 & Valley)',
    shortName: 'DHA Islamabad',
    city: 'Islamabad',
    deliveryType: 'Dedicated Rider Express Delivery',
    deliveryFee: 'Standard Rider Delivery',
    deliveryTimeMorning: '6:00 AM – 8:30 AM',
    deliveryTimeEvening: '5:00 PM – 7:30 PM',
    description: 'Daily fresh organic cow milk delivery across DHA Islamabad Phases 1, 2, 3, 5 and DHA Valley. Guaranteed unpasteurized pure farm freshness.',
    landmarks: ['DHA Phase 2 Central Park', 'World Trade Center Giga Mall Area', 'DHA Phase 1 Commercial', 'Sector F DHA 2'],
    postalCode: '44000',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'Bilona Cow Desi Ghee', 'Probiotic Dahi', 'Fresh Cream'],
  },
  {
    slug: 'sector-f-6-f-7-f-8',
    name: 'Sectors F-6, F-7 & F-8 (Super, Jinnah & Ayub Markaz)',
    shortName: 'Sectors F-6, F-7, F-8',
    city: 'Islamabad',
    deliveryType: 'Dedicated Rider Express Delivery',
    deliveryFee: 'Standard Rider Delivery',
    deliveryTimeMorning: '6:00 AM – 8:15 AM',
    deliveryTimeEvening: '5:00 PM – 7:15 PM',
    description: 'Premium fresh cow milk delivery for residents of F-6, F-7 (Jinnah Super), and F-8 (Ayub Market). Delivered chilled in food-grade sealed bottles.',
    landmarks: ['Super Market F-6', 'Jinnah Super Market F-7', 'Ayub Market F-8', 'Kohsar Market'],
    postalCode: '44000',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'A2 Cow Milk Selection', 'Bilona Desi Ghee', 'Artisan Paneer'],
  },
  {
    slug: 'sector-f-10-f-11',
    name: 'Sectors F-10 & F-11 (F-10 Markaz & F-11 Markaz)',
    shortName: 'Sectors F-10, F-11',
    city: 'Islamabad',
    deliveryType: 'Dedicated Rider Express Delivery',
    deliveryFee: 'Standard Rider Delivery',
    deliveryTimeMorning: '6:15 AM – 8:30 AM',
    deliveryTimeEvening: '5:00 PM – 7:30 PM',
    description: 'Fresh milk morning delivery routes servicing all streets of Sector F-10 and Sector F-11. 100% free of preservatives and water dilution.',
    landmarks: ['F-10 Markaz', 'F-11 Markaz', 'Silver Oaks Area', 'Margalla Road Avenue'],
    postalCode: '44000',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'Slow-Churned Desi Ghee', 'Thick Organic Dahi'],
  },
  {
    slug: 'sector-g-10-g-11-g-13',
    name: 'Sectors G-10, G-11 & G-13',
    shortName: 'Sectors G-10, G-11, G-13',
    city: 'Islamabad',
    deliveryType: 'Dedicated Rider Express Delivery',
    deliveryFee: 'Standard Rider Delivery',
    deliveryTimeMorning: '6:30 AM – 8:45 AM',
    deliveryTimeEvening: '5:15 PM – 7:30 PM',
    description: 'Doorstep cow milk delivery servicing G-10, G-11, and G-13 Markaz and residential streets. Fresh morning delivery directly from the farm.',
    landmarks: ['G-10 Markaz', 'G-11 Markaz', 'G-13 Markaz', 'Kashmir Highway Link'],
    postalCode: '44000',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'Fresh Dahi', 'Bilona Ghee', 'Pure Butter'],
  },
  {
    slug: 'sector-e-7-e-11',
    name: 'Sectors E-7, E-11 & MPCHS',
    shortName: 'Sectors E-7, E-11',
    city: 'Islamabad',
    deliveryType: 'Dedicated Rider Express Delivery',
    deliveryFee: 'Standard Rider Delivery',
    deliveryTimeMorning: '6:00 AM – 8:15 AM',
    deliveryTimeEvening: '5:00 PM – 7:15 PM',
    description: 'Chilled delivery of pure pasture cow milk across Sector E-7 and E-11 (Northern Strip, MPCHS, Golra Road). Lab tested and unadulterated.',
    landmarks: ['Margalla Avenue', 'E-11/2 & E-11/3 Markaz', 'Shaheen Chowk', 'E-7 Embassy Road'],
    postalCode: '44000',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'Bilona Desi Ghee', 'Organic Dahi', 'Fresh Makhan'],
  },
  {
    slug: 'gulberg-greens-islamabad',
    name: 'Gulberg Greens & Gulberg Residencia',
    shortName: 'Gulberg Greens',
    city: 'Islamabad',
    deliveryType: 'Dedicated Rider Express Delivery',
    deliveryFee: 'Standard Rider Delivery',
    deliveryTimeMorning: '6:15 AM – 8:30 AM',
    deliveryTimeEvening: '5:00 PM – 7:30 PM',
    description: 'Express morning milk delivery throughout Gulberg Greens Farmhouses (Executive, Coral, Spring) and Gulberg Residencia blocks.',
    landmarks: ['Gulberg Greens Main Boulevard', 'Civic Center Gulberg', 'Korang River Avenue'],
    postalCode: '44000',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'Bilona Desi Ghee', 'Fresh Cream', 'Natural Dahi'],
  },
  {
    slug: 'rawalpindi-saddar-cantt',
    name: 'Rawalpindi Saddar, Cantt & Westridge',
    shortName: 'Rawalpindi Cantt / Saddar',
    city: 'Rawalpindi',
    deliveryType: 'Dedicated Rider Express Delivery',
    deliveryFee: 'Standard Rider Delivery',
    deliveryTimeMorning: '6:00 AM – 8:30 AM',
    deliveryTimeEvening: '5:00 PM – 7:30 PM',
    description: 'Daily morning fresh cow milk delivery for Rawalpindi Saddar, Cantt, Chaklala Scheme 3, and Westridge families. Pure and adulterant-free.',
    landmarks: ['Saddar Rawalpindi', 'Peshawar Road', 'Chaklala Scheme 3', 'Westridge 1 & 2'],
    postalCode: '46000',
    popularProducts: ['Pure Cow Milk (Rs. 250/L)', 'Pure Desi Ghee (Bilona)', 'Probiotic Dahi', 'Natural Butter'],
  },
];

export function getAreaBySlug(slug: string): DeliveryAreaSEO | undefined {
  return DELIVERY_AREAS.find((area) => area.slug === slug);
}
